### ISSUE TITLE
Conversion Factor not working for GeV**-3 to fm**3

### ISSUE THREAD

**Issue by RJaBi** [AndreScaffidi/NatPy#1]
When I try to get the conversion factor for GeV^-3 to fm^3 the code fails with an astropy.units.core.UnitConversionError . I.e.

```
import astropy.units as u
import natpy
natpy.convert( u.GeV**(-3), u.fm**3 )
```
fails with the error message.
```
Traceback (most recent call last):
  File "/home/RJaBi/miniconda3/envs/datathon/lib/python3.8/site-packages/natpy/convert.py", line 89, in convert
    return initial_unit.to(target_unit)
  File "/home/RJaBi/miniconda3/envs/datathon/lib/python3.8/site-packages/astropy/units/core.py", line 987, in to
    return self._get_converter(other, equivalencies=equivalencies)(value)
  File "/home/RJaBi/miniconda3/envs/datathon/lib/python3.8/site-packages/astropy/units/core.py", line 918, in _get_converter
    raise exc
  File "/home/RJaBi/miniconda3/envs/datathon/lib/python3.8/site-packages/astropy/units/core.py", line 903, in _get_converter
    return self._apply_equivalencies(
  File "/home/RJaBi/miniconda3/envs/datathon/lib/python3.8/site-packages/astropy/units/core.py", line 886, in _apply_equivalencies
    raise UnitConversionError(
astropy.units.core.UnitConversionError: '1 / GeV3' and 'fm3' (volume) are not convertible

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/RJaBi/miniconda3/envs/datathon/lib/python3.8/site-packages/natpy/convert.py", line 95, in convert
    return UnitConvert(initial_unit, target_unit, natural_matrix, natural_bases)
  File "/home/RJaBi/miniconda3/envs/datathon/lib/python3.8/site-packages/natpy/convert.py", line 74, in UnitConvert
    raise UnitConversionError(f"Units {initial_unit} and {target_unit} not compatible after considering natural dimensionality.")
astropy.units.core.UnitConversionError: Units 1 / GeV3 and fm3 not compatible after considering natural dimensionality.
```

However when I try and actually convert a number (rather than get the conversion factor) the code works as expected.
```
import astropy.units as u
import natpy
natpy.convert( 1*u.GeV**(-3), u.fm**3 )
```
gives
`<Quantity 0.00768351 fm3>`

which is correct.

**Comment by AndreScaffidi** [comment]
Hello Ryan,

This issue was resolved in the latest patch [0.0.3](https://pypi.org/project/NatPy/).

Andre
